# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cheating_list_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SentimentListItem(object):
    def setupUi(self, SentimentListItem):
        SentimentListItem.setObjectName("SentimentListItem")
        SentimentListItem.setWindowModality(QtCore.Qt.NonModal)
        SentimentListItem.setEnabled(True)
        SentimentListItem.resize(196, 41)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SentimentListItem)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl = QtWidgets.QLabel(SentimentListItem)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(7)
        self.lbl.setFont(font)
        self.lbl.setMouseTracking(False)
        self.lbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl.setLineWidth(0)
        self.lbl.setTextFormat(QtCore.Qt.RichText)
        self.lbl.setOpenExternalLinks(False)
        self.lbl.setObjectName("lbl")
        self.horizontalLayout.addWidget(self.lbl)

        self.retranslateUi(SentimentListItem)
        QtCore.QMetaObject.connectSlotsByName(SentimentListItem)

    def retranslateUi(self, SentimentListItem):
        _translate = QtCore.QCoreApplication.translate
        SentimentListItem.setWindowTitle(_translate("SentimentListItem", "cheating_list_item"))
        self.lbl.setText(_translate("SentimentListItem", "lbl"))
